"""Durable job queue over pgmq, with a plain-table fallback.

Forge's batch-boundary hygiene jobs used to be fire-and-forget: a crashed
batch silently skipped them. This adapter makes them survivable messages —
pgmq (in-database queue with visibility timeouts and an archive) when the
extension is installed, otherwise a plain table drained with
``FOR UPDATE SKIP LOCKED`` (same crash-safety, fewer features).

Semantics (both backends):
- ``send`` enqueues a JSON-able dict.
- ``read`` returns at most one message and hides it for ``vt`` seconds; a
  consumer that crashes mid-job simply lets the message reappear.
- ``archive`` finalizes a message exactly once. Consumers must be idempotent
  (key their side effects, e.g. ``project_id:job_type:day``) because
  redelivery after a crash is by design.

Every method is best-effort: queue failures degrade to "no message", never
to a crashed batch.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any, Optional

from sqlalchemy import text

QUEUE = "forge_hygiene"
FALLBACK_TABLE = "forge_queue_fallback"


@dataclass(frozen=True)
class QueueMessage:
    msg_id: int
    payload: dict[str, Any]


class DurableQueue:
    def __init__(self, db, queue: str = QUEUE) -> None:
        self.db = db
        self.queue = queue

    # -- backend detection ---------------------------------------------------

    def backend(self) -> str:
        try:
            if self.db.bind.dialect.name == "postgresql":
                has = self.db.execute(text(
                    "SELECT 1 FROM pg_extension WHERE extname = 'pgmq'")).scalar()
                if has:
                    return "pgmq"
        except Exception:
            self.db.rollback()
        return "fallback"

    def _ensure_fallback_table(self) -> None:
        self.db.execute(text(f"""
            CREATE TABLE IF NOT EXISTS {FALLBACK_TABLE} (
                msg_id INTEGER PRIMARY KEY {"GENERATED BY DEFAULT AS IDENTITY" if self.db.bind.dialect.name == "postgresql" else "AUTOINCREMENT"},
                queue TEXT NOT NULL,
                payload TEXT NOT NULL,
                visible_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                archived_at TIMESTAMP
            )"""))
        self.db.commit()

    # -- API -------------------------------------------------------------

    def send(self, payload: dict[str, Any]) -> Optional[int]:
        try:
            if self.backend() == "pgmq":
                row = self.db.execute(
                    text("SELECT * FROM pgmq.send(:q, CAST(:msg AS jsonb))"),
                    {"q": self.queue, "msg": json.dumps(payload)}).scalar()
                self.db.commit()
                return int(row)
            self._ensure_fallback_table()
            result = self.db.execute(
                text(f"INSERT INTO {FALLBACK_TABLE} (queue, payload) "
                     "VALUES (:q, :p)"),
                {"q": self.queue, "p": json.dumps(payload)})
            self.db.commit()
            return result.lastrowid if hasattr(result, "lastrowid") else None
        except Exception:
            self.db.rollback()
            return None

    def read(self, vt: int = 60) -> Optional[QueueMessage]:
        try:
            if self.backend() == "pgmq":
                row = self.db.execute(
                    text("SELECT msg_id, message FROM pgmq.read(:q, :vt, 1)"),
                    {"q": self.queue, "vt": vt}).fetchone()
                self.db.commit()
                if not row:
                    return None
                payload = row[1] if isinstance(row[1], dict) else json.loads(row[1])
                return QueueMessage(msg_id=int(row[0]), payload=payload)
            self._ensure_fallback_table()
            lock = " FOR UPDATE SKIP LOCKED" if self.db.bind.dialect.name == "postgresql" else ""
            row = self.db.execute(text(
                f"SELECT msg_id, payload FROM {FALLBACK_TABLE} "
                "WHERE queue = :q AND archived_at IS NULL "
                "AND visible_at <= CURRENT_TIMESTAMP "
                f"ORDER BY msg_id LIMIT 1{lock}"),
                {"q": self.queue}).fetchone()
            if not row:
                self.db.rollback()
                return None
            if self.db.bind.dialect.name == "postgresql":
                self.db.execute(text(
                    f"UPDATE {FALLBACK_TABLE} SET visible_at = "
                    "CURRENT_TIMESTAMP + make_interval(secs => :vt) "
                    "WHERE msg_id = :id"), {"vt": vt, "id": row[0]})
            else:
                self.db.execute(text(
                    f"UPDATE {FALLBACK_TABLE} SET visible_at = "
                    "datetime(CURRENT_TIMESTAMP, '+' || :vt || ' seconds') "
                    "WHERE msg_id = :id"), {"vt": vt, "id": row[0]})
            self.db.commit()
            return QueueMessage(msg_id=int(row[0]), payload=json.loads(row[1]))
        except Exception:
            self.db.rollback()
            return None

    def archive(self, msg_id: int) -> bool:
        try:
            if self.backend() == "pgmq":
                ok = self.db.execute(
                    text("SELECT pgmq.archive(:q, :id)"),
                    {"q": self.queue, "id": msg_id}).scalar()
                self.db.commit()
                return bool(ok)
            self._ensure_fallback_table()
            self.db.execute(text(
                f"UPDATE {FALLBACK_TABLE} SET archived_at = CURRENT_TIMESTAMP "
                "WHERE msg_id = :id AND archived_at IS NULL"), {"id": msg_id})
            self.db.commit()
            return True
        except Exception:
            self.db.rollback()
            return False
