"""Build the tool documentation database (`tool_docs.db`) and emit the always-in-
context capability summary (`CAPABILITIES.md`).

This is the single source of truth for *what tools/skills/frameworks the Hermes
agent has access to, where they live, and when to use them*. The DB holds the
FULL docs (pulled on demand by the agent via `get_tool_doc`); CAPABILITIES.md is
the short always-loaded index injected into SOUL context.

Re-run after adding/changing a tool:
    python tools_db/build_tool_docs.py
"""
import os
import sqlite3
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(HERE, "tool_docs.db")
CAPS_MD = os.path.join(HERE, "CAPABILITIES.md")
SOUL_MD = os.path.expanduser("~/.hermes/SOUL.md")
SOUL_BEGIN = "<!-- BEGIN CAPABILITIES (auto-generated by tools_db/build_tool_docs.py) -->"
SOUL_END = "<!-- END CAPABILITIES (auto) -->"

# name, category, location, when_to_use, full_doc
TOOLS = [
    # ---- Core file & shell ----
    ("bash", "core", "Hermes native (terminal backend; e2b sandbox)",
     "Run shell commands: build, test, git, file ops, process control.",
     "Execute a shell command. Prefer dedicated tools (grep/glob/read/write) when they fit. "
     "On this setup code execution is routed through `process(action='run', command=...)` to the "
     "e2b cloud sandbox; do not assume host execution. Quote paths; avoid interactive flags."),
    ("grep", "core", "Hermes native (ripgrep)",
     "Search file CONTENTS by regex across the repo.",
     "Content search. Use for finding symbols, strings, call sites. Supports regex, globs, and "
     "output modes (files-with-matches, content, count). Faster and safer than `bash grep`."),
    ("glob", "core", "Hermes native",
     "Find FILES by name/path pattern (e.g. **/*.py).",
     "Path/name matching. Use to locate files by extension or naming convention before reading."),
    ("read_file", "core", "Hermes native (tools/file_operations.py)",
     "Read a file's contents (text, images, PDFs, notebooks).",
     "Read before editing. Prefer targeted ranges for large files."),
    ("write_file / edit", "core", "Hermes native (tools/file_operations.py)",
     "Create or modify files with exact edits.",
     "Write creates/overwrites; edit does exact string replacement. Always read a file before editing it."),
    # ---- Code execution / harnesses ----
    ("code_execution (python)", "execution", "Hermes native (tools/code_execution_tool.py) -> e2b",
     "Run Python for data work, scripts, quick computation, tests.",
     "Executes Python in the e2b sandbox. Use for deterministic logic, parsing, data analysis, "
     "and validation scripts rather than reasoning through computation in-context."),
    ("opencode", "execution", "e2b sandbox (`opencode-ai`, preinstalled)",
     "Delegate larger autonomous coding tasks to the OpenCode agent.",
     "Headless coding agent available in the sandbox. Use for multi-file implementation/refactors "
     "when a focused sub-agent coding loop is better than step-by-step edits."),
    ("pi", "execution", "e2b sandbox (`@mariozechner/pi-coding-agent`, preinstalled, global `pi`)",
     "Alternate coding harness for autonomous implementation tasks.",
     "The Pi coding agent. Use as a coding harness in the sandbox for build/fix loops."),
    ("e2b sandbox", "execution", "Cloud (e2b terminal backend)",
     "Isolated environment where ALL code execution runs.",
     "All `run_command`/`execute` are normalized to synchronous e2b runs. Treat it as the execution host; "
     "host-level execution is disabled."),
    # ---- Web & browser ----
    ("web (search/fetch)", "web", "Hermes toolset `web`",
     "Search the web and fetch/extract page content for research.",
     "Use for current facts, docs, and grounding. Capture URLs and dates. Configured aux task `web_extract` "
     "handles extraction."),
    ("browser (browser_navigate/click/type/snapshot/vision)", "web", "Hermes native toolset `browser`",
     "Drive a real browser: navigate, click, type, scroll, snapshot, visual check.",
     "Native browser_* tools. Workflow: browser_navigate -> browser_snapshot (page structure) -> "
     "browser_click / browser_type by element ref -> browser_vision for visual verification. "
     "Use for dynamic sites, logins, and UI automation when plain fetch is insufficient."),
    ("context7", "web", "MCP: context7 (mcp_context7_* tools)",
     "Fetch up-to-date library/framework/API documentation.",
     "Use BEFORE coding against a library to get current API syntax — even for well-known libs. "
     "Resolve the library id, then pull docs."),
    # ---- Delegation ----
    ("delegate / subagents", "delegation", "Hermes native (tools/delegate_tool.py)",
     "Spawn focused sub-agents for parallel inspection or narrow tasks.",
     "Use for independent exploration (inspect frontend, backend, tests, schema) then consolidate into one "
     "patch. Capped per platform config. Avoid overlapping edits."),
    # ---- PGE / Postgres memory (the autonomy backbone) ----
    ("pge_memory (Postgres tools)", "memory_pge",
     "Native Hermes plugin toolset `pge` (~/.hermes/plugins/pge) + DB at postgresql:///hermes_memory",
     "Persistent project/goal/task/memory state for long-horizon autonomous work.",
     "Direct Postgres-backed memory, tool names prefixed pge_: pge_create_project, pge_create_goal, "
     "pge_create_task, pge_set_active_task, pge_complete_task (evidence-gated), pge_record_decision, "
     "pge_record_file_change, pge_record_test_run, pge_create_checkpoint, pge_build_context_pack, "
     "pge_search_memory, pge_run_autonomy_loop. Call pge_build_context_pack at session start; "
     "pge_create_checkpoint before ending a turn."),
    ("lessons (continuous learning)", "memory_pge",
     "Native Hermes plugin toolset `pge`: pge_record_lesson / pge_recall_lessons",
     "Persist lessons from failures and proven recipes; recall them before similar work.",
     "pge_record_lesson(situation, lesson, category, importance) saves a lesson permanently; top lessons "
     "auto-load into every session via pge_build_context_pack. pge_recall_lessons(query) retrieves lessons "
     "relevant to the current situation — call it before retrying work that previously failed."),
    ("PGE framework (Planner-Generator-Evaluator)", "framework",
     "~/Developer/hermes_memory (run_pge.py + agent-autonomy-project/)",
     "Run a fully autonomous plan->execute->evaluate loop over the Postgres state.",
     "LangGraph loop: planner proposes/selects tasks, executor does one concrete step with tools, evaluator "
     "verifies completion against real evidence (file change / test run). Entry: `python run_pge.py "
     "--project <uuid> --goal '...' --desc '...'`. Worker LLM calls use reasoning_effort=none + json_schema for "
     "reliable structured output. Loop self-terminates (turn ceiling / no tasks / blocked). The DB is the durable "
     "state, so re-running resumes. Use the pge_run_autonomy_loop tool to trigger it from within Hermes."),
    ("pge_get_tool_doc / pge_list_tool_docs", "meta",
     "Native Hermes plugin toolset `pge` (~/.hermes/plugins/pge), DB tools_db/tool_docs.db",
     "Look up the FULL documentation for any tool by name, on demand.",
     "CAPABILITIES.md (this index) is always loaded into SOUL context; call pge_get_tool_doc('<name>') to pull the "
     "complete doc for a specific tool instead of guessing its interface. pge_list_tool_docs enumerates everything."),
]


def build_db():
    con = sqlite3.connect(DB_PATH)
    cur = con.cursor()
    cur.execute("""
        CREATE TABLE IF NOT EXISTS tools (
            name TEXT PRIMARY KEY,
            category TEXT NOT NULL,
            location TEXT NOT NULL,
            when_to_use TEXT NOT NULL,
            full_doc TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
    """)
    now = datetime.now(timezone.utc).isoformat()
    for name, cat, loc, when, doc in TOOLS:
        cur.execute(
            "INSERT INTO tools(name,category,location,when_to_use,full_doc,updated_at) VALUES (?,?,?,?,?,?) "
            "ON CONFLICT(name) DO UPDATE SET category=excluded.category, location=excluded.location, "
            "when_to_use=excluded.when_to_use, full_doc=excluded.full_doc, updated_at=excluded.updated_at",
            (name, cat, loc, when, doc, now),
        )
    con.commit()
    n = cur.execute("SELECT COUNT(*) FROM tools").fetchone()[0]
    con.close()
    return n


def emit_capabilities_md():
    con = sqlite3.connect(DB_PATH)
    cur = con.cursor()
    # Registry-synced rows (category 'hermes:<toolset>', written by
    # sync_registry_docs.py) are deep docs pulled on demand — exclude them
    # from the always-loaded index so SOUL.md stays lean.
    rows = cur.execute(
        "SELECT category,name,location,when_to_use FROM tools "
        "WHERE category NOT LIKE 'hermes:%' ORDER BY "
        "CASE category WHEN 'core' THEN 0 WHEN 'execution' THEN 1 WHEN 'web' THEN 2 "
        "WHEN 'delegation' THEN 3 WHEN 'memory_pge' THEN 4 WHEN 'framework' THEN 5 ELSE 6 END, name"
    ).fetchall()
    con.close()

    cat_titles = {
        "core": "Core file & shell", "execution": "Code execution & harnesses",
        "web": "Web & browser", "delegation": "Delegation", "memory_pge": "Persistent memory (Postgres/PGE)",
        "framework": "Frameworks", "meta": "Meta / docs",
    }
    lines = [
        "# Hermes Capability Index (always loaded)",
        "",
        "_Authoritative list of tools/skills/frameworks you have access to. This is the INDEX "
        "(name · location · when to use). For full usage of any item call the "
        "`pge_get_tool_doc` tool — do not guess an interface._",
        "",
        f"_Generated from `tools_db/tool_docs.db` — {len(rows)} entries._",
        "",
    ]
    current = None
    for cat, name, loc, when in rows:
        if cat != current:
            current = cat
            lines.append(f"## {cat_titles.get(cat, cat)}")
        lines.append(f"- **{name}** — _{loc}_ — {when}")
    lines.append("")
    with open(CAPS_MD, "w") as f:
        f.write("\n".join(lines))
    return len(rows)


def sync_soul():
    """Inject the capability index into SOUL.md (always-loaded context) inside a
    managed marker block, so the agent always sees the current tool list."""
    if not os.path.exists(SOUL_MD):
        return False
    caps = open(CAPS_MD).read().strip()
    block = (
        f"{SOUL_BEGIN}\n"
        "# CAPABILITIES — what tools you have and when to use them\n"
        "(Auto-synced from `~/Developer/hermes_memory/tools_db/tool_docs.db`. "
        "For full usage of any item, call the `pge_get_tool_doc` tool.)\n\n"
        f"{caps}\n"
        f"{SOUL_END}"
    )
    soul = open(SOUL_MD).read()
    if SOUL_BEGIN in soul and SOUL_END in soul:
        pre = soul.split(SOUL_BEGIN)[0]
        post = soul.split(SOUL_END, 1)[1]
        soul = pre + block + post
    else:
        # Prepend so it is the first thing in the persona context.
        soul = block + "\n\n" + soul
    open(SOUL_MD, "w").write(soul)
    return True


if __name__ == "__main__":
    n = build_db()
    m = emit_capabilities_md()
    synced = sync_soul()
    print(f"tool_docs.db: {n} tools  ->  {DB_PATH}")
    print(f"CAPABILITIES.md: {m} entries  ->  {CAPS_MD}")
    print(f"SOUL.md synced: {synced}  ->  {SOUL_MD}")
